
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: pinglog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-cnf
      containers:
      - name: logoutput
        image: pyryl/logoutput@sha256:4167c16f57e8b8063d12508c0f4f0f84afe8f3bcd243dc9858750aae0deefa94
        env:
        - name: PORT
          value: '3000'
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-cnf
              key: message
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/config
      - name: loginput
        image: pyryl/loginput@sha256:a04dbe1b8771e2af061379942592d859f3bdb3872b421a1270517fcaf0aac01a
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
