
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
      - name: logoutput
        image: pyryl/logoutput@sha256:39c23ade78055c0b17a8c15c597391d16682404307110d077150ff9ea551a581
        env:
        - name: PORT
          value: '3000'
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      - name: loginput
        image: pyryl/loginput@sha256:516ab1c6530e9670f45cfdc029a2bb9c3b8ce2b8baf054c0235c55e7b08b7855
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
