
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: pinglog
spec:
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: pyryl/pingpong@sha256:aa22b94a2094e8cdf46b9a23dda68a46b4880faf29a0380cb376d2dda9f57720
        env:
        - name: PORT
          value: '3000'
        envFrom:
        - secretRef:
            name: pingpong-postgres-password
