
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: pinglog
spec:
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: pyryl/pingpong@sha256:71db3e8cbd9ceb929baac8e6ff857ecd160a384dd2a84f9737397c261e317905
        env:
        - name: PORT
          value: '3000'
        envFrom:
        - secretRef:
            name: pingpong-postgres-password
