
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingpong-postgres-stset
  namespace: pinglog
spec:
  selector:
    matchLabels:
      app: pingpong-postgres
  serviceName: pingpong-postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: pingpong-postgres
    spec:
      containers:
      - name: pingpong-postgres
        image: pyryl/pingpong-postgres@sha256:de2f052807dca3ee544af3ba14f5aed7082eb1f06ef2676aad9b74c175d85307
        envFrom:
        - secretRef:
            name: pingpong-postgres-password
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: postgres-data-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: pingpong-postgres-svc
  namespace: pinglog
spec:
  selector:
    app: pingpong-postgres
  ports:
  - port: 5432
    targetPort: 5432
