
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-dep
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: todo-project-pvc
      containers:
      - name: todo-project
        image: PROJECT/NAME
        env:
        - name: PORT
          value: '3000'
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
