
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - persistent_volume_claim.yaml
  - ../../misc/todo_persistent_volume.yaml
images:
  - name: PROJECT/NAME
    newName: pyryl/todo-project@sha256:e2a496c9a82c28b9012c203a9671f7a7b36ffd8d14a70ac579783f904650c173
