
apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-project-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-dwk-cluster-default-pool-7c25e8ab-07dn
